training:
  batch_size: 128
  n_epochs: 100
  algo: "ssm_vr"
  noise_type: "radermacher"
data:
  dataset: "CIFAR10"
  image_size: 32
  channels: 3
  noise_sigma: 0.1
model:
  hidden_size: 1000
  num_layers: 5 # only 2 or 5
optim:
  weight_decay: 0.00
  optimizer: "Adam"
  lr: 0.00003